version: '3.8'

services:
  goodnightworld:
    build: .
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - goodnight-network
#    depends_on:
#      - postgres

#  postgres:
#    image: postgres:15-alpine
#    environment:
#      POSTGRES_DB: goodnightdb
#      POSTGRES_PASSWORD: password
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - goodnight-network

networks:
  goodnight-network:

#volumes:
#  postgres_data: